# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget redis++::redis++_static redis++::redis++)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target redis++::redis++_static
add_library(redis++::redis++_static STATIC IMPORTED)

set_target_properties(redis++::redis++_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src/sw/redis++/no_tls;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src/sw/redis++/cxx17;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src;/usr/local/include"
)

# Create imported target redis++::redis++
add_library(redis++::redis++ SHARED IMPORTED)

set_target_properties(redis++::redis++ PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src/sw/redis++/no_tls;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src/sw/redis++/cxx17;/home/rsb/rms/device_end/redis-plus-plus-1.3.14/src;/usr/local/include"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libhiredis.a"
)

# Import target "redis++::redis++_static" for configuration "Release"
set_property(TARGET redis++::redis++_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(redis++::redis++_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/rsb/rms/device_end/redis-plus-plus-1.3.14/libredis++.a"
  )

# Import target "redis++::redis++" for configuration "Release"
set_property(TARGET redis++::redis++ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(redis++::redis++ PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/rsb/rms/device_end/redis-plus-plus-1.3.14/libredis++.so.1.3.14"
  IMPORTED_SONAME_RELEASE "libredis++.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
